version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGUSER: postgres
      PGPASSWORD: lvm25
      PGDATABASE: niver_db
      PGPORT: 5432

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lvm25
      POSTGRES_DB: niver_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: andre@pmr.dev
      PGADMIN_DEFAULT_PASSWORD: lvm25
    ports:
      - "5050:80"

volumes:
  pgdata:
